### ISSUE TITLE
stop sound on page load

### ISSUE THREAD

**Issue by saniko** [SharePointOscar/MEANS#20]
where can i modify this?

**Comment by SharePointOscar** [comment]
What sound are you referring to?  There are no sound files on this boilerplate template.

**Comment by saniko** [comment]
Each time I'm refreshing the page or navigating to new page, there a sound ,  maybe I'm using old template?

Sent from Yahoo Mail on Android

**Comment by johntom** [comment]
i get that on my windows 8 computers. Perhaps that's the issue.

**Comment by saniko** [comment]
Yep, I'm using window 8, happens only on this project.

Sent from Yahoo Mail on Android

**Comment by SharePointOscar** [comment]
Closing this as we do not use any sound files whatsoever.  It could be a page transition on Windows Explorer, but certainly not related to the boilerplate template.  @saniko feel free to research it on your pull request, but I could not find an issue.

**Comment by johntom** [comment]
Hi Oscar,

How the F are you?

I've implemented a cms with our means repo and would love to show you.

John

**Comment by johntom** [comment]
System took a dump when I tried to present. Sorry for delay. Please send # to call u on
